# Generated by Django 5.0 on 2025-12-05 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('os_type', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='up', max_length=20)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('open_ports', models.JSONField(default=list)),
                ('services', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['ip_address'],
            },
        ),
        migrations.CreateModel(
            name='SecurityTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nmap', 'Nmap'), ('zap', 'OWASP ZAP'), ('openvas', 'OpenVAS'), ('trivy', 'Trivy'), ('tshark', 'TShark'), ('wazuh', 'Wazuh')], max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scanning', 'Scanning'), ('error', 'Error')], default='inactive', max_length=20)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('scan_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='security_ap_metric__7684d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('raw_output', models.TextField()),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='security_api.securitytool')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('intrusion', 'Intrusion Attempt'), ('malware', 'Malware Detected'), ('vulnerability', 'New Vulnerability'), ('anomaly', 'Anomalous Behavior'), ('policy_violation', 'Policy Violation'), ('scan_complete', 'Scan Complete')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security_api.securitytool')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='security_ap_timesta_0c513d_idx'), models.Index(fields=['severity', 'acknowledged'], name='security_ap_severit_d815ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cve_id', models.CharField(blank=True, max_length=50, null=True)),
                ('affected_asset', models.CharField(max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remediation', models.TextField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='security_api.securitytool')),
            ],
            options={
                'ordering': ['-discovered_at', 'severity'],
                'indexes': [models.Index(fields=['severity', 'status'], name='security_ap_severit_f9820a_idx'), models.Index(fields=['discovered_at'], name='security_ap_discove_c100e1_idx')],
            },
        ),
    ]
